### ISSUE TITLE
Other Language Translations

### ISSUE THREAD

**Issue by BolajiOlajide** [andela-rbabalola/slack-translate-project#1]
Hello,

I think you should update the `README` to show what other language variations we are allowed access to.
Also, is it only `en-es` translation that the application offers.

Thanks.

**Comment by rotimi-babalola** [comment]
The list is very long. Too long to be in the `README` I put a [link](https://tech.yandex.com/translate/doc/dg/concepts/api-overview-docpage/) in the `README`

Also `en-es` is just an example. Other languages are supported by the API
